#!/bin/bash

# Note: script was generated by Claude 3.7 Sonnet

echo "Starting to update all git repositories in $(pwd)"
echo "------------------------------------------------"

# Loop through all directories in the current location
for dir in */; do
    # Remove trailing slash
    dir=${dir%/}
    
    echo "Checking $dir..."
    
    # Check if directory is a git repository
    if [ -d "$dir/.git" ]; then
        echo "Updating repository: $dir"
        (cd "$dir" && git pull)
        echo "------------------------------------------------"
    else
        echo "Skipping $dir - not a git repository"
        echo "------------------------------------------------"
    fi
done

echo "All repositories have been processed!"
