#!/bin/bash

# Note: script was generated by Claude 3.7 Sonnet

echo "Starting repository organization script"
echo "======================================="

# Loop through all directories in the current location
for dir in */; do
    # Remove trailing slash
    dir=${dir%/}
    
    echo "Checking subdirectory '$dir'..."
    
    # Check if directory is a git repository
    if [ -d "$dir/.git" ]; then
        echo "  '$dir' is a git repository"
        
        # Get remote URL
        remote_url=$(cd "$dir" && git remote get-url origin 2>/dev/null)
        
        if [ -z "$remote_url" ]; then
            echo "  No remote URL found for '$dir', skipping"
            echo "--------------------------------------"
            continue
        fi
        
        echo "  Cloned from '$remote_url'"
        
        # Extract owner from GitHub URL
        if [[ $remote_url =~ github.com[:/]([^/]+)/[^/]+(.git)? ]]; then
            owner="${BASH_REMATCH[1]}"
            echo "  Owner is '$owner'"
            
            # Check if owner directory exists
            if [ ! -d "$owner" ]; then
                echo "  Directory '$owner' does not exist, creating directory"
                mkdir -p "$owner"
            else
                echo "  Directory '$owner' already exists"
            fi
            
            # Check if target directory already exists
            if [ -d "$owner/$dir" ]; then
                echo "  WARNING: Target directory '$owner/$dir' already exists, skipping"
                echo "--------------------------------------"
                continue
            fi
            
            echo "  Moving repo '$dir' to subdirectory '$owner/$dir'"
            mv "$dir" "$owner/"
            echo "  Done"
        else
            echo "  Could not extract owner from URL '$remote_url', skipping"
        fi
    else
        echo "  '$dir' is not a git repository, skipping"
    fi
    
    echo "--------------------------------------"
done

echo "Repository organization completed!"
